/**
 * AI View Types and Interfaces — barrel re-export for backward compatibility
 * This file has been split into ai-types/ directory.
 * All imports from this path continue to work unchanged.
 */
export type {
	// Model config
	AIModelEndpoints,
	UpscaleModelEndpoints,
	AIModelParameters,
	UpscaleModelParameters,
	ModelCategory,
	AIModel,
	// Generation
	GeneratedVideo,
	GeneratedVideoResult,
	PollingState,
	AIServiceManager,
	ProgressUpdate,
	ProgressCallback,
	GenerationStatus,
	APIConfiguration,
	AIError,
	// Hook props & state
	UseAIGenerationProps,
	AIGenerationState,
	UseAIHistoryProps,
	AIHistoryState,
	AIActiveTab,
	AvatarUploadState,
	ImageUploadState,
	// Request types
	VideoGenerationRequest,
	ImageToVideoRequest,
	TextToVideoRequest,
	ViduQ2I2VRequest,
	ViduQ3T2VRequest,
	ViduQ3I2VRequest,
	LTXV2T2VRequest,
	LTXV2I2VRequest,
	LTX23T2VRequest,
	LTX23I2VRequest,
	LTX23A2VRequest,
	HappyHorseT2VRequest,
	HappyHorseRef2VRequest,
	HappyHorseVideoEditRequest,
	HappyHorseDuration,
	HappyHorseResolution,
	HappyHorseAspectRatio,
	HappyHorseAudioSetting,
	AvatarVideoRequest,
	VideoGenerationResponse,
	ModelsResponse,
	CostEstimate,
	SeedanceI2VRequest,
	Seedance2I2VRequest,
	Seedance2Ref2VRequest,
	KlingI2VRequest,
	Kling26I2VRequest,
	KlingO1V2VRequest,
	KlingO1Ref2VideoRequest,
	WAN25I2VRequest,
	WAN26T2VRequest,
	WAN26I2VRequest,
	WAN26Ref2VideoRequest,
	ByteDanceUpscaleRequest,
	FlashVSRUpscaleRequest,
	TopazUpscaleRequest,
	// Lipsync
	SyncLipsyncEmotion,
	SyncLipsyncModelMode,
	SyncLipsyncSyncMode,
	SyncLipsyncReact1Request,
	// Sora 2
	Sora2ModelType,
	Sora2BasePayload,
	Sora2Payload,
	// Seeddream
	Seeddream45ImageSize,
	Seeddream45TextToImageParams,
	Seeddream45EditParams,
	// Convenience aliases
	Model,
	Video,
	VideoResult,
	Polling,
	ServiceManager,
	GenerationState,
	HistoryState,
} from "./ai-types/index";
