-- Additive safety follow-up for 20260811000000_seed_qcut_catalog_pricing.sql.
-- Rate-priced rows cannot use the flat credits hold until rate-aware reserve exists.
-- Newly inserted rows are quarantined from shared catalog surfaces until metadata is sourced.
BEGIN;
UPDATE public.ai_model_catalog
SET credits = 0,
    enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    supports = ARRAY[]::text[],
    payload_keys = ARRAY[]::text[],
    requires_assets = ARRAY[]::text[],
    time_label = '',
    pricing = pricing || '{"billable":false,"billing_status":"rate_pending"}'::jsonb,
    updated_at = now()
WHERE pricing->>'source' = 'qcut-credit-price-table'
  AND pricing->>'unit' <> 'per_request'
  AND pricing->>'minimum_credits' = '1'
  AND credits = 1;
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    name = id,
    description = '',
    category = '',
    workflow_type = '',
    supports = ARRAY[]::text[],
    payload_keys = ARRAY[]::text[],
    requires_assets = ARRAY[]::text[],
    time_label = '',
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    aliases = ARRAY[]::text[],
    updated_at = now()
WHERE provider = 'fal-ai'
  AND description = 'QCut Fal catalog endpoint.'
  AND pricing->>'source' = 'qcut-credit-price-table'
  AND enabled = TRUE;
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'fal-ai/bytedance/seedance/v1/lite/image-to-video'
  AND credits = 1
  AND pricing_text = '0 credits'
  AND pricing = '{"raw":"0 credits","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'fal-ai/ffmpeg-api/compose'
  AND credits = 1
  AND pricing_text = '0 credits'
  AND pricing = '{"raw":"0 credits","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'fal-ai/ffmpeg-api/extract-frame'
  AND credits = 1
  AND pricing_text = '0 credits'
  AND pricing = '{"raw":"0 credits","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'fal-ai/ffmpeg-api/loudnorm'
  AND credits = 1
  AND pricing_text = '0 credits'
  AND pricing = '{"raw":"0 credits","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'fal-ai/ffmpeg-api/merge-audios'
  AND credits = 1
  AND pricing_text = '0 credits'
  AND pricing = '{"raw":"0 credits","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'fal-ai/ffmpeg-api/merge-audio-video'
  AND credits = 1
  AND pricing_text = '0 credits'
  AND pricing = '{"raw":"0 credits","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'fal-ai/ffmpeg-api/merge-videos'
  AND credits = 1
  AND pricing_text = '0 credits'
  AND pricing = '{"raw":"0 credits","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'fal-ai/ffmpeg-api/metadata'
  AND credits = 1
  AND pricing_text = '0 credits'
  AND pricing = '{"raw":"0 credits","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'fal-ai/ffmpeg-api/waveform'
  AND credits = 1
  AND pricing_text = '0 credits'
  AND pricing = '{"raw":"0 credits","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'fal-ai/kling-video/o3/pro/image-to-video'
  AND credits = 1
  AND pricing_text = '0 credits'
  AND pricing = '{"raw":"0 credits","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'fal-ai/kling-video/o3/pro/reference-to-video'
  AND credits = 1
  AND pricing_text = '0 credits'
  AND pricing = '{"raw":"0 credits","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'fal-ai/kling-video/o3/pro/video-to-video/edit'
  AND credits = 1
  AND pricing_text = '0 credits'
  AND pricing = '{"raw":"0 credits","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'fal-ai/kling-video/o3/pro/video-to-video/reference'
  AND credits = 1
  AND pricing_text = '0 credits'
  AND pricing = '{"raw":"0 credits","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'fal-ai/kling-video/o3/standard/reference-to-video'
  AND credits = 1
  AND pricing_text = '0 credits'
  AND pricing = '{"raw":"0 credits","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'fal-ai/kling-video/o3/standard/video-to-video/edit'
  AND credits = 1
  AND pricing_text = '0 credits'
  AND pricing = '{"raw":"0 credits","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'fal-ai/ltx-2-19b/distilled/extend-video'
  AND credits = 1
  AND pricing_text = '0 credits'
  AND pricing = '{"raw":"0 credits","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'fal-ai/ltx-2-19b/text-to-video'
  AND credits = 1
  AND pricing_text = '0 credits'
  AND pricing = '{"raw":"0 credits","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'fal-ai/ltx-video'
  AND credits = 1
  AND pricing_text = '0 credits'
  AND pricing = '{"raw":"0 credits","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'fal-ai/magi'
  AND credits = 1
  AND pricing_text = '0 credits'
  AND pricing = '{"raw":"0 credits","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'fal-ai/magi/image-to-video'
  AND credits = 1
  AND pricing_text = '0 credits'
  AND pricing = '{"raw":"0 credits","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'fal-ai/qwen-image-2512'
  AND credits = 1
  AND pricing_text = '0 credits'
  AND pricing = '{"raw":"0 credits","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'fal-ai/qwen-image-2/pro/edit'
  AND credits = 1
  AND pricing_text = '0 credits'
  AND pricing = '{"raw":"0 credits","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'fal-ai/qwen-image-2/pro/text-to-image'
  AND credits = 1
  AND pricing_text = '0 credits'
  AND pricing = '{"raw":"0 credits","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'fal-ai/qwen-image-edit-2509'
  AND credits = 1
  AND pricing_text = '0 credits'
  AND pricing = '{"raw":"0 credits","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'fal-ai/qwen-image-edit-2511-multiple-angles'
  AND credits = 1
  AND pricing_text = '0 credits'
  AND pricing = '{"raw":"0 credits","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'fal-ai/qwen-image-edit-plus-lora-gallery/multiple-angles'
  AND credits = 1
  AND pricing_text = '0 credits'
  AND pricing = '{"raw":"0 credits","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'fal-ai/qwen-image-layered'
  AND credits = 1
  AND pricing_text = '0 credits'
  AND pricing = '{"raw":"0 credits","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'fal-ai/seedream/v4.5/edit'
  AND credits = 1
  AND pricing_text = '0 credits'
  AND pricing = '{"raw":"0 credits","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'fal-ai/seedream/v5/lite/edit'
  AND credits = 1
  AND pricing_text = '0 credits'
  AND pricing = '{"raw":"0 credits","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'fal-ai/seedream/v5/lite/text-to-image'
  AND credits = 1
  AND pricing_text = '0 credits'
  AND pricing = '{"raw":"0 credits","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'fal-ai/sora-2/video-to-video/remix'
  AND credits = 1
  AND pricing_text = '0 credits'
  AND pricing = '{"raw":"0 credits","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'fal-ai/workflow-utilities/audio-compressor'
  AND credits = 1
  AND pricing_text = '0 credits'
  AND pricing = '{"raw":"0 credits","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'fal-ai/workflow-utilities/blend-video'
  AND credits = 1
  AND pricing_text = '0 credits'
  AND pricing = '{"raw":"0 credits","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'fal-ai/workflow-utilities/extract-nth-frame'
  AND credits = 1
  AND pricing_text = '0 credits'
  AND pricing = '{"raw":"0 credits","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'fal-ai/workflow-utilities/impulse-response'
  AND credits = 1
  AND pricing_text = '0 credits'
  AND pricing = '{"raw":"0 credits","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'fal-ai/workflow-utilities/interleave-video'
  AND credits = 1
  AND pricing_text = '0 credits'
  AND pricing = '{"raw":"0 credits","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'fal-ai/workflow-utilities/reverse-video'
  AND credits = 1
  AND pricing_text = '0 credits'
  AND pricing = '{"raw":"0 credits","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'fal-ai/workflow-utilities/scale-video'
  AND credits = 1
  AND pricing_text = '0 credits'
  AND pricing = '{"raw":"0 credits","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'fal-ai/workflow-utilities/trim-video'
  AND credits = 1
  AND pricing_text = '0 credits'
  AND pricing = '{"raw":"0 credits","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/anthropic-claude-haiku-4-5'
  AND credits = 0
  AND pricing_text = 'Input: 1.00 per 1M tokens; Output: 5.00 per 1M tokens'
  AND pricing = '{"raw":"Input: 1.00 per 1M tokens; Output: 5.00 per 1M tokens","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/anthropic-claude-opus-4-1'
  AND credits = 0
  AND pricing_text = 'Input: 15.00 per 1M tokens; Output: 75.00 per 1M tokens'
  AND pricing = '{"raw":"Input: 15.00 per 1M tokens; Output: 75.00 per 1M tokens","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/anthropic-claude-opus-4-5'
  AND credits = 0
  AND pricing_text = 'Input: 5.00 per 1M tokens; Output: 25.00 per 1M tokens'
  AND pricing = '{"raw":"Input: 5.00 per 1M tokens; Output: 25.00 per 1M tokens","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/anthropic-claude-opus-4-6'
  AND credits = 0
  AND pricing_text = 'Input: 5.00 per 1M tokens; Output: 25.00 per 1M tokens'
  AND pricing = '{"raw":"Input: 5.00 per 1M tokens; Output: 25.00 per 1M tokens","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/anthropic-claude-sonnet-4'
  AND credits = 0
  AND pricing_text = 'Input: 3.00 per 1M tokens; Output: 15.00 per 1M tokens'
  AND pricing = '{"raw":"Input: 3.00 per 1M tokens; Output: 15.00 per 1M tokens","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/anthropic-claude-sonnet-4-5'
  AND credits = 0
  AND pricing_text = 'Input: 3.00 per 1M tokens; Output: 15.00 per 1M tokens'
  AND pricing = '{"raw":"Input: 3.00 per 1M tokens; Output: 15.00 per 1M tokens","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/anthropic-claude-sonnet-4-6'
  AND credits = 0
  AND pricing_text = 'Input: 3.00 per 1M tokens; Output: 15.00 per 1M tokens'
  AND pricing = '{"raw":"Input: 3.00 per 1M tokens; Output: 15.00 per 1M tokens","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/bria-genfill'
  AND credits = 0
  AND pricing_text = 'Not disclosed (expected to be low)'
  AND pricing = '{"raw":"Not disclosed (expected to be low)","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/bria-video-eraser'
  AND credits = 0
  AND pricing_text = 'Not disclosed'
  AND pricing = '{"raw":"Not disclosed","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/claude-opus-4.7'
  AND credits = 0
  AND pricing_text = 'Pricing not available.'
  AND pricing = '{"raw":"Pricing not available.","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/deepseek-ai-deepseek-r1'
  AND credits = 0
  AND pricing_text = 'Input: 0.50 per 1M tokens; Output: 2.18 per 1M tokens'
  AND pricing = '{"raw":"Input: 0.50 per 1M tokens; Output: 2.18 per 1M tokens","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/deepseek-ai-deepseek-r1-distill-llama-70b'
  AND credits = 0
  AND pricing_text = 'Input: 0.25 per 1M tokens; Output: 0.75 per 1M tokens'
  AND pricing = '{"raw":"Input: 0.25 per 1M tokens; Output: 0.75 per 1M tokens","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/deepseek-ai-deepseek-r1-distill-llama-8b'
  AND credits = 0
  AND pricing_text = 'Input: 0.14 per 1M tokens; Output: 0.39 per 1M tokens'
  AND pricing = '{"raw":"Input: 0.14 per 1M tokens; Output: 0.39 per 1M tokens","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/deepseek-ai-deepseek-r1-distill-qwen-14b'
  AND credits = 0
  AND pricing_text = 'Input: 0.20 per 1M tokens; Output: 0.20 per 1M tokens'
  AND pricing = '{"raw":"Input: 0.20 per 1M tokens; Output: 0.20 per 1M tokens","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/deepseek-ai-deepseek-r1-distill-qwen-32b'
  AND credits = 0
  AND pricing_text = 'Input: 0.50 per 1M tokens; Output: 0.90 per 1M tokens'
  AND pricing = '{"raw":"Input: 0.50 per 1M tokens; Output: 0.90 per 1M tokens","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/deepseek-ai-deepseek-r1-distill-qwen-7b'
  AND credits = 0
  AND pricing_text = 'Input: 0.10 per 1M tokens; Output: 0.20 per 1M tokens'
  AND pricing = '{"raw":"Input: 0.10 per 1M tokens; Output: 0.20 per 1M tokens","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/deepseek-ai-deepseek-v3-0324'
  AND credits = 0
  AND pricing_text = 'Input: 0.18 per 1M tokens; Output: 0.60 per 1M tokens'
  AND pricing = '{"raw":"Input: 0.18 per 1M tokens; Output: 0.60 per 1M tokens","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/deepseek-ai-deepseek-v3-1'
  AND credits = 0
  AND pricing_text = 'Input: 0.27 per 1M tokens; Output: 1.00 per 1M tokens'
  AND pricing = '{"raw":"Input: 0.27 per 1M tokens; Output: 1.00 per 1M tokens","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/deepseek-ai-deepseek-v3-1-terminus'
  AND credits = 0
  AND pricing_text = 'Input: 0.27 per 1M tokens; Output: 1.00 per 1M tokens'
  AND pricing = '{"raw":"Input: 0.27 per 1M tokens; Output: 1.00 per 1M tokens","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/deepseek-ai-deepseek-v3-2'
  AND credits = 0
  AND pricing_text = 'Input: 0.20 per 1M tokens; Output: 0.32 per 1M tokens'
  AND pricing = '{"raw":"Input: 0.20 per 1M tokens; Output: 0.32 per 1M tokens","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/deepseek-ai-deepseek-v3-2-exp'
  AND credits = 0
  AND pricing_text = 'Input: 0.27 per 1M tokens; Output: 0.41 per 1M tokens'
  AND pricing = '{"raw":"Input: 0.27 per 1M tokens; Output: 0.41 per 1M tokens","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/deepseek-ai-deepseek-v3-2-speciale'
  AND credits = 0
  AND pricing_text = 'Input: 0.28 per 1M tokens; Output: 0.40 per 1M tokens'
  AND pricing = '{"raw":"Input: 0.28 per 1M tokens; Output: 0.40 per 1M tokens","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/deepseek-r1'
  AND credits = 0
  AND pricing_text = 'Input: 0.40 per 1M tokens; Output: 1.80 per 1M tokens'
  AND pricing = '{"raw":"Input: 0.40 per 1M tokens; Output: 1.80 per 1M tokens","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/deepseek-v4-pro'
  AND credits = 0
  AND pricing_text = 'Input: $1.392 per 1M tokens; Output: $2.784 per 1M tokens'
  AND pricing = '{"raw":"Input: $1.392 / Output: $2.784 per 1M tokens","credits":0,"inputUsdPer1M":1.392,"outputUsdPer1M":2.784}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/elevenlabs-tts-multilingual-v2'
  AND credits = 0
  AND pricing_text = 'Not disclosed'
  AND pricing = '{"raw":"Not disclosed","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/elevenlabs-tts-v3'
  AND credits = 0
  AND pricing_text = 'Not disclosed (depends on usage)'
  AND pricing = '{"raw":"Not disclosed (depends on usage)","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/gemini-3.1-flash-lite'
  AND credits = 0
  AND pricing_text = 'Input: 0.25 per 1M tokens; Output: 1.50 per 1M tokens'
  AND pricing = '{"raw":"Input: 0.25 per 1M tokens; Output: 1.50 per 1M tokens","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/glm-5'
  AND credits = 0
  AND pricing_text = 'Open-source, hosted via GMI'
  AND pricing = '{"raw":"Open-source, hosted via GMI","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/glm-5.1'
  AND credits = 0
  AND pricing_text = 'Open-source, hosted via GMI'
  AND pricing = '{"raw":"Open-source, hosted via GMI","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/google-gemini-3-1-pro-preview'
  AND credits = 0
  AND pricing_text = 'Input: 2.00 per 1M tokens; Output: 12.00 per 1M tokens'
  AND pricing = '{"raw":"Input: 2.00 per 1M tokens; Output: 12.00 per 1M tokens","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/google-gemma-4-26b-a4b-it'
  AND credits = 0
  AND pricing_text = 'Input: 0.13 per 1M tokens; Output: 0.40 per 1M tokens'
  AND pricing = '{"raw":"Input: 0.13 per 1M tokens; Output: 0.40 per 1M tokens","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/google-gemma-4-31b-it'
  AND credits = 0
  AND pricing_text = 'Input: 0.14 per 1M tokens; Output: 0.40 per 1M tokens'
  AND pricing = '{"raw":"Input: 0.14 per 1M tokens; Output: 0.40 per 1M tokens","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/kling-image2video-v2-1-lite'
  AND credits = 0
  AND pricing_text = 'Not disclosed (expected lower than Pro/Master tiers)'
  AND pricing = '{"raw":"Not disclosed (expected lower than Pro/Master tiers)","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/meta-llama-llama-3-3-70b-instruct'
  AND credits = 0
  AND pricing_text = 'Input: 0.25 per 1M tokens; Output: 0.75 per 1M tokens'
  AND pricing = '{"raw":"Input: 0.25 per 1M tokens; Output: 0.75 per 1M tokens","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/meta-llama-llama-4-maverick-17b-128e-instruct-fp8'
  AND credits = 0
  AND pricing_text = 'Input: 0.25 per 1M tokens; Output: 0.80 per 1M tokens'
  AND pricing = '{"raw":"Input: 0.25 per 1M tokens; Output: 0.80 per 1M tokens","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/meta-llama-llama-4-scout-17b-16e-instruct'
  AND credits = 0
  AND pricing_text = 'Input: 0.08 per 1M tokens; Output: 0.50 per 1M tokens'
  AND pricing = '{"raw":"Input: 0.08 per 1M tokens; Output: 0.50 per 1M tokens","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/minimaxai-minimax-m2'
  AND credits = 0
  AND pricing_text = 'Input: 0.30 per 1M tokens; Output: 1.20 per 1M tokens'
  AND pricing = '{"raw":"Input: 0.30 per 1M tokens; Output: 1.20 per 1M tokens","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/minimaxai-minimax-m2-1'
  AND credits = 0
  AND pricing_text = 'Input: 0.30 per 1M tokens; Output: 1.20 per 1M tokens'
  AND pricing = '{"raw":"Input: 0.30 per 1M tokens; Output: 1.20 per 1M tokens","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/minimaxai-minimax-m2-5'
  AND credits = 0
  AND pricing_text = 'Input: 0.30 per 1M tokens; Output: 1.20 per 1M tokens'
  AND pricing = '{"raw":"Input: 0.30 per 1M tokens; Output: 1.20 per 1M tokens","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/minimaxai-minimax-m2-7'
  AND credits = 0
  AND pricing_text = 'Input: 0.30 per 1M tokens; Output: 1.20 per 1M tokens'
  AND pricing = '{"raw":"Input: 0.30 per 1M tokens; Output: 1.20 per 1M tokens","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/minimax-audio-voice-clone-speech-2-6-hd'
  AND credits = 0
  AND pricing_text = 'Not disclosed'
  AND pricing = '{"raw":"Not disclosed","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/minimax-audio-voice-clone-speech-2-6-turbo'
  AND credits = 0
  AND pricing_text = 'Not disclosed'
  AND pricing = '{"raw":"Not disclosed","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/minimax-tts-speech-01-hd'
  AND credits = 0
  AND pricing_text = 'Not disclosed'
  AND pricing = '{"raw":"Not disclosed","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/minimax-tts-speech-01-turbo'
  AND credits = 0
  AND pricing_text = 'Not disclosed'
  AND pricing = '{"raw":"Not disclosed","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/minimax-tts-speech-02-hd'
  AND credits = 0
  AND pricing_text = 'Not disclosed'
  AND pricing = '{"raw":"Not disclosed","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/minimax-tts-speech-2-5-hd-preview'
  AND credits = 0
  AND pricing_text = 'Not disclosed'
  AND pricing = '{"raw":"Not disclosed","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/minimax-tts-speech-2-5-turbo-preview'
  AND credits = 0
  AND pricing_text = 'Not disclosed (preview tier)'
  AND pricing = '{"raw":"Not disclosed (preview tier)","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/minimax-tts-speech-2-6-hd'
  AND credits = 0
  AND pricing_text = 'Not disclosed (higher than Turbo tier)'
  AND pricing = '{"raw":"Not disclosed (higher than Turbo tier)","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/moonshotai-kimi-k2-5'
  AND credits = 0
  AND pricing_text = 'Input: 0.60 per 1M tokens; Output: 3.00 per 1M tokens'
  AND pricing = '{"raw":"Input: 0.60 per 1M tokens; Output: 3.00 per 1M tokens","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/moonshotai-kimi-k2-instruct-0905'
  AND credits = 0
  AND pricing_text = 'Input: 0.30 per 1M tokens; Output: 1.70 per 1M tokens'
  AND pricing = '{"raw":"Input: 0.30 per 1M tokens; Output: 1.70 per 1M tokens","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/moonshotai-kimi-k2-thinking'
  AND credits = 0
  AND pricing_text = 'Input: 0.80 per 1M tokens; Output: 1.20 per 1M tokens'
  AND pricing = '{"raw":"Input: 0.80 per 1M tokens; Output: 1.20 per 1M tokens","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/openai-gpt-4o'
  AND credits = 0
  AND pricing_text = 'Input: 2.25 per 1M tokens; Output: 9.00 per 1M tokens'
  AND pricing = '{"raw":"Input: 2.25 per 1M tokens; Output: 9.00 per 1M tokens","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/openai-gpt-5'
  AND credits = 0
  AND pricing_text = 'Input: 1.13 per 1M tokens; Output: 9.00 per 1M tokens'
  AND pricing = '{"raw":"Input: 1.13 per 1M tokens; Output: 9.00 per 1M tokens","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/openai-gpt-5-1'
  AND credits = 0
  AND pricing_text = 'Input: 1.13 per 1M tokens; Output: 9.00 per 1M tokens'
  AND pricing = '{"raw":"Input: 1.13 per 1M tokens; Output: 9.00 per 1M tokens","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/openai-gpt-5-1-chat'
  AND credits = 0
  AND pricing_text = 'Input: 1.13 per 1M tokens; Output: 9.00 per 1M tokens'
  AND pricing = '{"raw":"Input: 1.13 per 1M tokens; Output: 9.00 per 1M tokens","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/openai-gpt-5-2'
  AND credits = 0
  AND pricing_text = 'Input: 1.58 per 1M tokens; Output: 12.60 per 1M tokens'
  AND pricing = '{"raw":"Input: 1.58 per 1M tokens; Output: 12.60 per 1M tokens","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/openai-gpt-5-2-chat'
  AND credits = 0
  AND pricing_text = 'Input: 1.58 per 1M tokens; Output: 12.60 per 1M tokens'
  AND pricing = '{"raw":"Input: 1.58 per 1M tokens; Output: 12.60 per 1M tokens","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/openai-gpt-5-2-codex'
  AND credits = 0
  AND pricing_text = 'Input: 1.58 per 1M tokens; Output: 12.60 per 1M tokens'
  AND pricing = '{"raw":"Input: 1.58 per 1M tokens; Output: 12.60 per 1M tokens","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/openai-gpt-5-3-codex'
  AND credits = 0
  AND pricing_text = 'Input: 1.58 per 1M tokens; Output: 12.60 per 1M tokens'
  AND pricing = '{"raw":"Input: 1.58 per 1M tokens; Output: 12.60 per 1M tokens","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/openai-gpt-5-4'
  AND credits = 0
  AND pricing_text = 'Input: 2.25 per 1M tokens; Output: 13.50 per 1M tokens'
  AND pricing = '{"raw":"Input: 2.25 per 1M tokens; Output: 13.50 per 1M tokens","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/openai-gpt-5-4-mini'
  AND credits = 0
  AND pricing_text = 'Input: 0.68 per 1M tokens; Output: 4.05 per 1M tokens'
  AND pricing = '{"raw":"Input: 0.68 per 1M tokens; Output: 4.05 per 1M tokens","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/openai-gpt-5-4-nano'
  AND credits = 0
  AND pricing_text = 'Input: 0.18 per 1M tokens; Output: 1.13 per 1M tokens'
  AND pricing = '{"raw":"Input: 0.18 per 1M tokens; Output: 1.13 per 1M tokens","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/openai-gpt-5-4-pro'
  AND credits = 0
  AND pricing_text = 'Input: 27.00 per 1M tokens; Output: 162.00 per 1M tokens'
  AND pricing = '{"raw":"Input: 27.00 per 1M tokens; Output: 162.00 per 1M tokens","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/openai-gpt-5.5'
  AND credits = 0
  AND pricing_text = 'See OpenAI pricing'
  AND pricing = '{"raw":"See OpenAI pricing","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/openai-o4-mini'
  AND credits = 0
  AND pricing_text = 'Input: 0.14 per 1M tokens; Output: 0.54 per 1M tokens'
  AND pricing = '{"raw":"Input: 0.14 per 1M tokens; Output: 0.54 per 1M tokens","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/qwen-qwen3-30b-a3b'
  AND credits = 0
  AND pricing_text = 'Input: 0.08 per 1M tokens; Output: 0.25 per 1M tokens'
  AND pricing = '{"raw":"Input: 0.08 per 1M tokens; Output: 0.25 per 1M tokens","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/qwen-qwen3-5-122b-a10b'
  AND credits = 0
  AND pricing_text = 'Input: 0.40 per 1M tokens; Output: 3.20 per 1M tokens'
  AND pricing = '{"raw":"Input: 0.40 per 1M tokens; Output: 3.20 per 1M tokens","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/qwen-qwen3-5-27b'
  AND credits = 0
  AND pricing_text = 'Input: 0.30 per 1M tokens; Output: 2.40 per 1M tokens'
  AND pricing = '{"raw":"Input: 0.30 per 1M tokens; Output: 2.40 per 1M tokens","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/qwen-qwen3-5-35b-a3b'
  AND credits = 0
  AND pricing_text = 'Input: 0.25 per 1M tokens; Output: 2.00 per 1M tokens'
  AND pricing = '{"raw":"Input: 0.25 per 1M tokens; Output: 2.00 per 1M tokens","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/qwen-qwen3-5-397b-a17b'
  AND credits = 0
  AND pricing_text = 'Input: 0.60 per 1M tokens; Output: 3.60 per 1M tokens'
  AND pricing = '{"raw":"Input: 0.60 per 1M tokens; Output: 3.60 per 1M tokens","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/qwen-qwen3-next-80b-a3b-instruct'
  AND credits = 0
  AND pricing_text = 'Input: 0.15 per 1M tokens; Output: 1.50 per 1M tokens'
  AND pricing = '{"raw":"Input: 0.15 per 1M tokens; Output: 1.50 per 1M tokens","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/qwen-qwen3-next-80b-a3b-thinking'
  AND credits = 0
  AND pricing_text = 'Input: 0.15 per 1M tokens; Output: 1.50 per 1M tokens'
  AND pricing = '{"raw":"Input: 0.15 per 1M tokens; Output: 1.50 per 1M tokens","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/reve-create-20250915'
  AND credits = 0
  AND pricing_text = 'Not disclosed'
  AND pricing = '{"raw":"Not disclosed","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/reve-edit-20250915'
  AND credits = 0
  AND pricing_text = 'Not disclosed'
  AND pricing = '{"raw":"Not disclosed","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/reve-edit-fast-20251030'
  AND credits = 0
  AND pricing_text = 'Not disclosed'
  AND pricing = '{"raw":"Not disclosed","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/reve-remix-20250915'
  AND credits = 0
  AND pricing_text = 'Not disclosed'
  AND pricing = '{"raw":"Not disclosed","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/reve-remix-fast-20251030'
  AND credits = 0
  AND pricing_text = 'Not disclosed'
  AND pricing = '{"raw":"Not disclosed","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/seededit-3-0-i2i-250628'
  AND credits = 0
  AND pricing_text = 'Not disclosed'
  AND pricing = '{"raw":"Not disclosed","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/seedream-3-0-t2i-250415'
  AND credits = 0
  AND pricing_text = 'Not publicly disclosed (likely similar to Seedream 4.0)'
  AND pricing = '{"raw":"Not publicly disclosed (likely similar to Seedream 4.0)","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/step-audio-editx'
  AND credits = 0
  AND pricing_text = 'Not disclosed'
  AND pricing = '{"raw":"Not disclosed","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/veo-3-1-fast-generate-preview'
  AND credits = 0
  AND pricing_text = 'Not disclosed; preview tier'
  AND pricing = '{"raw":"Not disclosed; preview tier","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/veo-3-1-generate-preview'
  AND credits = 0
  AND pricing_text = 'Not disclosed; preview tier'
  AND pricing = '{"raw":"Not disclosed; preview tier","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/veo3-fast'
  AND credits = 0
  AND pricing_text = 'Not publicly disclosed; expected lower than standard Veo 3 pricing'
  AND pricing = '{"raw":"Not publicly disclosed; expected lower than standard Veo 3 pricing","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/wan2-5-i2v-preview'
  AND credits = 0
  AND pricing_text = 'Not disclosed'
  AND pricing = '{"raw":"Not disclosed","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/wan2-5-t2v-preview'
  AND credits = 0
  AND pricing_text = 'Not disclosed (preview tier)'
  AND pricing = '{"raw":"Not disclosed (preview tier)","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/wan2-6-i2v'
  AND credits = 0
  AND pricing_text = 'Not publicly disclosed'
  AND pricing = '{"raw":"Not publicly disclosed","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/wan2-6-r2v'
  AND credits = 0
  AND pricing_text = 'Not publicly disclosed'
  AND pricing = '{"raw":"Not publicly disclosed","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/wan2.6-t2v'
  AND credits = 0
  AND pricing_text = 'Not publicly disclosed'
  AND pricing = '{"raw":"Not publicly disclosed","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/wan2.7-i2v'
  AND credits = 0
  AND pricing_text = 'Pricing not available.'
  AND pricing = '{"raw":"Pricing not available.","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/wan2.7-r2v'
  AND credits = 0
  AND pricing_text = 'Pricing not available.'
  AND pricing = '{"raw":"Pricing not available.","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/zai-org-glm-4-6'
  AND credits = 0
  AND pricing_text = 'Input: 0.60 per 1M tokens; Output: 2.00 per 1M tokens'
  AND pricing = '{"raw":"Input: 0.60 per 1M tokens; Output: 2.00 per 1M tokens","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/zai-org-glm-4-7-flash'
  AND credits = 0
  AND pricing_text = 'Input: 0.07 per 1M tokens; Output: 0.40 per 1M tokens'
  AND pricing = '{"raw":"Input: 0.07 per 1M tokens; Output: 0.40 per 1M tokens","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/zai-org-glm-4-7-fp8'
  AND credits = 0
  AND pricing_text = 'Input: 0.33 per 1M tokens; Output: 1.50 per 1M tokens'
  AND pricing = '{"raw":"Input: 0.33 per 1M tokens; Output: 1.50 per 1M tokens","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/zai-org-glm-5-fp8'
  AND credits = 0
  AND pricing_text = 'Input: 1.00 per 1M tokens; Output: 3.20 per 1M tokens'
  AND pricing = '{"raw":"Input: 1.00 per 1M tokens; Output: 3.20 per 1M tokens","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/z-image-fast'
  AND credits = 0
  AND pricing_text = 'Not disclosed'
  AND pricing = '{"raw":"Not disclosed","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
UPDATE public.ai_model_catalog
SET enabled = FALSE,
    studio_surfaces = ARRAY[]::text[],
    kanvas_modes = ARRAY[]::text[],
    updated_at = now()
WHERE id = 'gmi/z-image-turbo'
  AND credits = 0
  AND pricing_text = 'Not disclosed'
  AND pricing = '{"raw":"Not disclosed","credits":0}'::jsonb
  AND enabled = TRUE
  AND studio_surfaces = ARRAY[]::text[]
  AND kanvas_modes = ARRAY[]::text[];
COMMIT;
